### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by mattwelborn** [aspuru-guzik-group/group-selfies#1]
Thank you for making this code available! Based on your arXiv paper's abstract, this repository is meant to be open-source. However, it is not open-source until a license is added. Please add a(n open-source) license.

GitHub provides information on choosing a license here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

**Comment by auhcheng** [comment]
Added!
